services:
  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16.2
    environment:
      POSTGRES_USER: matelandia_user
      POSTGRES_PASSWORD: matelandia_password
      POSTGRES_DB: matelandia_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      
    stdin_open: true
    tty: true
    command: npm run serve

volumes:
  postgres_data:

networks:
  matelandia-network:
    driver: bridge